#!/usr/bin/env python3
from gachakelompok import (
    Parser, main_cli, console, pretty,
    read, show, delete, copy, rename
)


def main():
    # calling functions depending on type of argument
    parser = Parser()
    args = parser.parse_args()
    if args.start:
        return main_cli()
    if args.read:
        return read(args.read[0])
    elif args.show:
        return show(args.show[0])
    elif args.delete:
        return delete(args.delete[0])
    elif args.copy:
        return copy(args.copy[0], args.copy[1])
    elif args.rename:
        return rename(args.rename[0], args.rename[1])

    return main_cli()


if __name__ == "__main__":
    pretty.install(console)
    try:
        raise SystemExit(main())
    except (SystemExit, KeyboardInterrupt) as e:
        console.print(e)
        console.print("\n\n[green b]Program Ditutup[green b]")
